version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reading_recommendation
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/reading_recommendation
    ports:
      - "3000:3000"
    depends_on:
      - db
